apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: gomeet
  labels:
    app: livekit-sfu
    component: config
data:
  livekit.yaml: |
    # LiveKit Server Configuration
    port: 7880
    http_port: 7880
    rtc_port: 7881
    rtc_tcp_port: 7882
    rtc_tls_port: 7883

    redis:
      address: "thorough-orca-5577.upstash.io:6379"
      password: "ARYJAAImcDI4YTQ5NGM2MTM2YDQ0MDg1OWQxOWQxNjY3ZjI1ZjE0ZmQ2ZmY3NzdmNw=="
      db: 0
      
    keys:
      - key: "LK_KEY123"
        secret: "LK_SECRET456"
        
    room:
      auto_create: true
      empty_timeout: 300s
      max_participants: 500
      
    turn:
      enabled: true
      servers:
        - "turn:turn.filosofine.com:3478?transport=udp"
        - "turn:turn.filosofine.com:3478?transport=tcp"
        - "turns:turn.filosofine.com:5349"
      username: "gomeet_turn"
      credential: "turn_password_filosofine_2024"
      
    logging:
      pion_level: info
      level: info
      
    prometheus:
      enabled: true
      port: 6789
      
    development: false
