# =============================================================================
# GoMeet Clean Middleware Configuration
# DigitalOcean Kubernetes Cluster
#
# This file contains all middleware definitions in a clean, organized manner.
# =============================================================================

---
# HTTP to HTTPS Redirect Middleware (Global)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-https-redirect
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"

---
# Security Headers Middleware for Frontend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-frontend-security-headers
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: security-headers
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "meet.filosofine.com"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' wss: https: https://api-meet.filosofine.com; media-src 'self' blob:; frame-src 'self' https://livekit.filosofine.com;"

---
# Security Headers Middleware for API
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-api-security-headers
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: security-headers
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "api-meet.filosofine.com"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
      Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self' wss: https: https://meet.filosofine.com; media-src 'self' blob:;"

---
# Security Headers Middleware for LiveKit
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-livekit-security-headers
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: security-headers
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "livekit.filosofine.com"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"

---
# Rate Limiting Middleware for Frontend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-frontend-rate-limit
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: rate-limit
spec:
  rateLimit:
    average: 500
    burst: 1000
    period: 1m

---
# Rate Limiting Middleware for API
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-api-rate-limit
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: rate-limit
spec:
  rateLimit:
    average: 1000
    burst: 2000
    period: 1m

---
# Rate Limiting Middleware for WebSocket
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-rate-limit
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: rate-limit
spec:
  rateLimit:
    average: 2000
    burst: 4000
    period: 1m

---
# Rate Limiting Middleware for LiveKit
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-livekit-rate-limit
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: rate-limit
spec:
  rateLimit:
    average: 1500
    burst: 3000
    period: 1m

---
# CORS Middleware for API
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-api-cors
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: cors
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - Content-Type
      - Authorization
      - X-Requested-With
      - X-Forwarded-For
      - X-Real-IP
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    accessControlAllowOriginList:
      - "https://meet.filosofine.com"
      - "https://api-meet.filosofine.com"
    accessControlMaxAge: 86400

---
# WebSocket Headers Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-headers
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: websocket-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "api-meet.filosofine.com"
      X-Forwarded-For: "{{.ClientHost}}"
      Connection: "Upgrade"
      Upgrade: "websocket"
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "X-Forwarded-For"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "https://meet.filosofine.com"
      - "https://api-meet.filosofine.com"

---
# Compression Middleware for Frontend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-frontend-compression
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: compression
spec:
  compress:
    excludedContentTypes:
      - text/event-stream
      - application/grpc
      - application/wasm
    minResponseBodyBytes: 1024

---
# WebSocket Compression Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-compression
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: compression
spec:
  compress:
    excludedContentTypes:
      - text/event-stream
      - application/grpc
    minResponseBodyBytes: 512

---
# Circuit Breaker Middleware for API
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-api-circuit-breaker
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: circuit-breaker
spec:
  circuitBreaker:
    expression: "NetworkErrorRatio() > 0.2"
    checkPeriod: 5s
    fallbackDuration: 10s
    recoveryDuration: 10s

---
# WebSocket Circuit Breaker Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-circuit-breaker
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: circuit-breaker
spec:
  circuitBreaker:
    expression: "NetworkErrorRatio() > 0.1"
    checkPeriod: 3s
    fallbackDuration: 5s
    recoveryDuration: 5s

---
# Retry Middleware for API
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-api-retry
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: retry
spec:
  retry:
    attempts: 3
    initialInterval: 100ms

---
# IP Whitelist Middleware (Optional for Admin Access)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-admin-ip-whitelist
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: ip-whitelist
spec:
  ipWhiteList:
    sourceRange:
      - "127.0.0.1/32" # localhost
      - "10.0.0.0/8" # private networks
      - "172.16.0.0/12" # private networks
      - "192.168.0.0/16" # private networks

---
# Basic Auth Middleware (Optional for Admin Endpoints)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-admin-basic-auth
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: basic-auth
spec:
  basicAuth:
    # Use: htpasswd -nb admin password | base64
    # Example: admin:$apr1$d9hrkHm4$KXW8rVr8W8Q8rV8rV8rV8/
    secret: gomeet-admin-credentials

---
# Maintenance Mode Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-maintenance-mode
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: maintenance
spec:
  replacePathRegex:
    regex: "^/.*"
    replacement: "/maintenance.html"

---
# Request Size Limit Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-request-size-limit
  namespace: gomeet
  labels:
    app: gomeet
    component: middleware
    version: v2.0
    type: size-limit
spec:
  buffering:
    maxRequestBodyBytes: 10485760 # 10MB
    memRequestBodyBytes: 1048576 # 1MB
    maxResponseBodyBytes: 10485760 # 10MB
    memResponseBodyBytes: 1048576 # 1MB
    retryExpression: "IsNetworkError() && Attempts() < 2"
