apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-security-headers
  namespace: gomeet
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' wss: https:; media-src 'self' blob:;"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-rate-limit
  namespace: gomeet
spec:
  rateLimit:
    average: 1000
    burst: 2000
    period: 1m
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-rate-limit
  namespace: gomeet
spec:
  rateLimit:
    average: 2000
    burst: 4000
    period: 1m
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-cors
  namespace: gomeet
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - Content-Type
      - Authorization
      - X-Requested-With
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowOriginList:
      - "https://gomeet.com"
      - "https://www.gomeet.com"
      - "https://app.gomeet.com"
      - "https://api.gomeet.com"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-headers
  namespace: gomeet
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-For: "{{.ClientHost}}"
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "https://gomeet.com"
      - "https://api.gomeet.com"
      - "https://app.gomeet.com"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gomeet-websocket-compression
  namespace: gomeet
spec:
  compress:
    excludedContentTypes:
      - text/event-stream
      - application/grpc
    minResponseBodyBytes: 1024
