apiVersion: v1
kind: Pod
metadata:
  name: test-env
  namespace: gomeet
spec:
  containers:
    - name: test
      image: alpine:latest
      command: ["sleep", "3600"]
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: digitalocean-credentials
              key: DO_POSTGRES_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: digitalocean-credentials
              key: DO_POSTGRES_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: digitalocean-credentials
              key: DO_POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: digitalocean-credentials
              key: DO_POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: digitalocean-credentials
              key: DO_POSTGRES_DBNAME
  restartPolicy: Never
