# =============================================================================
# GoMeet Clean TLS Options Configuration
# DigitalOcean Kubernetes Cluster
#
# This file contains modern TLS configuration for optimal security and performance.
# =============================================================================

---
# Modern TLS Options for Production
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: modern
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    security-level: high
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # TLS 1.3 cipher suites (preferred)
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    # TLS 1.2 cipher suites (fallback)
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  sniStrict: true
  curvePreferences:
    - "CurveP521"
    - "CurveP384"
    - "CurveP256"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# Intermediate TLS Options for Compatibility
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: intermediate
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    security-level: medium
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # More compatible cipher suites for older clients
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
  sniStrict: false
  curvePreferences:
    - "CurveP521"
    - "CurveP384"
    - "CurveP256"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# Strict TLS Options for High-Security Applications
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: strict
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    security-level: maximum
spec:
  minVersion: "VersionTLS13"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Only TLS 1.3 cipher suites
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
  sniStrict: true
  curvePreferences:
    - "CurveP521"
    - "CurveP384"
    - "CurveP256"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# Legacy TLS Options for Maximum Compatibility
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: legacy
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    security-level: low
spec:
  minVersion: "VersionTLS10"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Include older cipher suites for legacy clients
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_RSA_WITH_AES_256_CBC_SHA256"
  sniStrict: false
  curvePreferences:
    - "CurveP521"
    - "CurveP384"
    - "CurveP256"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# WebSocket Optimized TLS Options
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: websocket
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    use-case: websocket
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Optimized for WebSocket performance
    - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_CHACHA20_POLY1305_SHA256"
    - "TLS_AES_128_GCM_SHA256"
  sniStrict: true
  curvePreferences:
    - "CurveP256" # Fastest curve for WebSocket
    - "CurveP384"
    - "CurveP521"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# API Optimized TLS Options
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: api
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    use-case: api
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Balanced for API performance and security
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_AES_128_GCM_SHA256"
  sniStrict: true
  curvePreferences:
    - "CurveP384"
    - "CurveP256"
    - "CurveP521"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# File Upload Optimized TLS Options
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: upload
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    use-case: file-upload
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Optimized for large file transfers
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_AES_128_GCM_SHA256"
  sniStrict: true
  curvePreferences:
    - "CurveP384" # Good balance of security and performance
    - "CurveP256"
    - "CurveP521"
  clientAuth:
    clientAuthType: "NoClientCert"

---
# Development/Testing TLS Options
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: development
  namespace: gomeet
  labels:
    app: gomeet
    component: tls-options
    version: v2.0
    environment: development
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    # Standard cipher suites for development
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  sniStrict: false # More lenient for development
  curvePreferences:
    - "CurveP256"
    - "CurveP384"
    - "CurveP521"
  clientAuth:
    clientAuthType: "NoClientCert"
